/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-wireless_dump
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_WIRELESS_DUMP_API_H
#define INCLUDED_WIRELESS_DUMP_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_wireless_dump_EXPORTS
#define WIRELESS_DUMP_API __GR_ATTR_EXPORT
#else
#define WIRELESS_DUMP_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_WIRELESS_DUMP_API_H */
