/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(dump_wifi_signal.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c34779ecb1bd0fdc1ec142bf97d57430)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/wireless_transformer/dump_wifi_signal.h>
// pydoc.h is automatically generated in the build directory
#include <dump_wifi_signal_pydoc.h>

void bind_dump_wifi_signal(py::module& m)
{

    using dump_wifi_signal    = gr::wireless_transformer::dump_wifi_signal;


    py::class_<dump_wifi_signal, gr::block, gr::basic_block,
        std::shared_ptr<dump_wifi_signal>>(m, "dump_wifi_signal", D(dump_wifi_signal))

        .def(py::init(&dump_wifi_signal::make),
           D(dump_wifi_signal,make)
        )
        



        ;




}








