function y = generate_wifi(opt)
    arguments
        opt.mod double = 0
        opt.psdu_length double = 10
    end

    mod = opt.mod;
    psdu_length = opt.psdu_length;

    % cfgHT = wlanHTConfig(...
    %     "ChannelBandwidth", "CBW20", ...
    %     "MCS", mod, ...
    %     "PSDULength", psdu_length);

    cfgNonHT = wlanNonHTConfig(...
        "ChannelBandwidth", "CBW20", ...
        "Modulation", "OFDM", ...
        "MCS", mod, ...
        "PSDULength", psdu_length);

    psdu = randi([0, 1], 8*psdu_length, 1);
    y = wlanWaveformGenerator(psdu, cfgNonHT);
end